COMPATIBILITY.md, Samples/statement_of_account.php, composer.json, composer.lock, lib/Fhp/Connection.php, lib/Fhp/Dialog/Dialog.php, lib/Fhp/FinTs.php, lib/Fhp/FinTsInternal.php, lib/Fhp/Model/StatementOfAccount/Transaction.php, lib/Fhp/Response/GetStatementOfAccount.php
Hi,
wir brauchten für unsere Buchhaltung den Geschäftsvorfall-Code aus dem Kontoauszug (booking_code im MT940). Dafür habe ich in der Klasse Fhp\Model\StatementOfAccount\Transaction einen getter/setter hinzugefügt.
Bei der Gelegenheit habe auch gleich eine Unterstützung für die Produkt-Registrierungsnummer eingebaut (Parameter 7 in der Fhp\FinTs Klasse) und die Minimum PHP-Version im Composer auf 5.6 erhöht.
Keine großen Sachen aber vielleicht nützlich...
Eine angepasste "Samples" Datei folgt noch.
Gruss, Markus
=> Support for booking_code and productName

lib/Fhp/Dialog/Dialog.php, lib/Fhp/FinTs.php, lib/Fhp/FinTsInternal.php
Discussion: https://github.com/nemiah/phpFinTS/issues/20#issuecomment-531487455
Clear `$this->dialog` in `FinTs::end()`. Continuing any communication on a closed dialog results in errors, obviously. Clearing it will tell `getDialog()` to initialize a new dialog.
In order to make sure that `FinTs::end()` is actually called, the `Dialog::syncDialog()` cannot (or rather: should not) implicitly end the dialog, so remove that functionality and instead call `FinTs::end()` at the respective call sites.
Note: I tried _not_ ending the dialog after calls like `getVariables()`, but apparently sending additional messages on the same dialog (e.g. fetching account statements) does not work.
=> Correctly end dialogs after sync

composer.json, composer.lock
We need a relatively old version because \PHPUnit_Framework_TestCase was replaced in v6.
=> Add PHPUnit as explicit dev dependency

lib/Fhp/Segment/BaseDeg.php, lib/Fhp/Segment/BaseDescriptor.php, lib/Fhp/Segment/BaseSegment.php, lib/Fhp/Segment/Common/Btg.php, lib/Fhp/Segment/DegDescriptor.php, lib/Fhp/Segment/ElementDescriptor.php, lib/Fhp/Segment/HITANS/HITANSv1.php, lib/Fhp/Segment/HITANS/HITANSv3.php, lib/Fhp/Segment/HITANS/ParameterZweiSchrittTanEinreichungV1.php, lib/Fhp/Segment/HITANS/ParameterZweiSchrittTanEinreichungV3.php, lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV1.php, lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV3.php, lib/Fhp/Segment/HIUPD/ErlaubteGeschaeftsvorfaelleV1.php, lib/Fhp/Segment/HIUPD/HIUPDv4.php, lib/Fhp/Segment/HIUPD/KontolimitV1.php, lib/Fhp/Segment/HIUPD/KtvV3.php, lib/Fhp/Segment/SegmentDescriptor.php, lib/Fhp/Segment/Segmentkopf.php, lib/Fhp/Syntax/Delimiter.php, lib/Fhp/Syntax/Parser.php, lib/Fhp/Syntax/Serializer.php, lib/Tests/Fhp/Segment/HITANSTest.php, lib/Tests/Fhp/Segment/HIUPDTest.php, lib/Tests/Fhp/Syntax/ParserTest.php, lib/Tests/Fhp/Syntax/SerializerTest.php
Currently, half of the segments (the ones that the client sends to the bank) are implemented as individual classes (e.g. `HKTAN`), whose constructor immediately serializes them to an array structure, which can require [cumbersome code](https://github.com/nemiah/phpFinTS/blob/4ca6c4fdd69ba7c59edbce2404e14239a5601cd4/lib/Fhp/Segment/HKTAN.php#L29-L59) when multiple versions need to be supported. The other half of the segments (the ones that the bank sends as a response) are stored as plain unparsed strings inside the `Response` class and [parsed on-the-fly](https://github.com/nemiah/phpFinTS/blob/4ca6c4fdd69ba7c59edbce2404e14239a5601cd4/lib/Fhp/Response/GetVariables.php#L14-L17) with a series of helper functions (`findSegments()`, `splitSegment()`, `splitDeg()`).
This pull request is a …
=> Redesign segments, DEGs and how they are parsed/serialized #26

lib/Fhp/FinTs.php
PHP 7 syntax was used here. PHP 5 syntax works just as well in this case.
=> Repair PHP 5 Support

lib/Fhp/Dialog/Dialog.php, lib/Fhp/FinTs.php
Sorgt dafür, dass auch beim initDialog ein fixer tanMechanism genutzt wird, statt des ersten aus der Liste aller erlaubten tanMechanisms.
Damit sollte später z.B. bei getSepaAccounts keine Probleme mehr auftauchen, denn dieser nutzt bereits den fixen tanMechanism.
=> Fix #43 sicherheitsprofil

lib/Fhp/Response/GetVariables.php, lib/Fhp/Segment/BaseSegment.php, lib/Fhp/Segment/HITANS/HITANS.php, lib/Fhp/Segment/HITANS/HITANSv1.php, lib/Fhp/Segment/HITANS/HITANSv2.php, lib/Fhp/Segment/HITANS/HITANSv3.php, lib/Fhp/Segment/HITANS/HITANSv4.php, lib/Fhp/Segment/HITANS/HITANSv5.php, lib/Fhp/Segment/HITANS/HITANSv6.php, lib/Fhp/Segment/HITANS/ParameterZweiSchrittTanEinreichung.php, lib/Fhp/Segment/HITANS/ParameterZweiSchrittTanEinreichungV1.php, lib/Fhp/Segment/HITANS/ParameterZweiSchrittTanEinreichungV2.php, lib/Fhp/Segment/HITANS/ParameterZweiSchrittTanEinreichungV3.php, lib/Fhp/Segment/HITANS/ParameterZweiSchrittTanEinreichungV4.php, lib/Fhp/Segment/HITANS/ParameterZweiSchrittTanEinreichungV5.php, lib/Fhp/Segment/HITANS/ParameterZweiSchrittTanEinreichungV6.php, lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahren.php, lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV1.php, lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV2.php, lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV3.php, lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV4.php, lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV5.php, lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV6.php, lib/Fhp/Syntax/Serializer.php, lib/Tests/Fhp/ResponseTest/GetVariablesTest.php, lib/Tests/Fhp/Segment/HITANSTest.php, lib/Tests/Fhp/Segment/HIUPDTest.php, lib/Tests/Fhp/Syntax/SerializerTest.php
This PR adds flexible parsing for `HITANS` segments version 1 through 6 and exposes the parsed segments with a common interface. This allows reimplementing `GetVariables:parseTanModes()` (which is a business logic layer function) without any interspersed parsing logic. If necessary, the common interface allows adding other `HITANS` versions without much thinking or danger of breaking other ones. The unit test remains unchanged besides plumbing.
@roben I'd appreciate your review, as you are probably most familiar with how `HITANS` works across the various banks. I'm not sure if your unit tests cover all the special cases that you considered when implementing the code. In particular, I see a comment about Sparkasse declaring version 6 and you suspecting that they send version 5, yet the …
=> Reimplement GetVariables based on new segments layer

lib/Fhp/FinTs.php, lib/Fhp/Model/StatementOfAccount/Transaction.php, lib/Fhp/Response/GetAccounts.php, lib/Fhp/Response/GetStatementOfAccount.php, lib/Fhp/Response/GetVariables.php, lib/Fhp/Response/Response.php
- getAccounts(): fixed at least for DKB and flatex. Gives all accounts including credit cards, SEPA accounts and securities accounts.
- GetAccounts.getAccountsArray(): ignores accounts without id (avoids error in the case of flatex)
- GetStatementAccount.addFromArray() + Transaction.php: added primanota number for statements
- GetVariables.get(): adds only allowed TAN methods into the list of all TAN methods
- isStrongAuthRequired(): adapted the flags to p. 24 of specification and the fields 'HIRMS' and 'HIRMG' are used for checking (needed e.g. for flatex)
- getSummaryBySegment(): displays the array attached to the message
=> Adds some smaller fixes and features

.travis.yml, phpunit.xml.dist
Remove deprecated syntaxCheck attribute from PhpUnit configuration. Make Travis use the PhpUnit version installed by Composer rather than the system-wide one. Update PHP versions to 7.2 and 7.3. Older versions (and nightly v8) are incompatible with PhpUnit 5.
Fixes https://github.com/nemiah/phpFinTS/issues/36
=> Fix Travis CI configuration

.travis.yml, disallowtabs.sh
Checks all added lines in the `git diff` for any tab characters that occur in the indentation part (i.e. before the first real non-whitespace character), and fails the Travis run if any tabs are found. Note that the Travis run is marked as failed but continues to run all others checks, so that the tabs can be ignored in individual cases.
Suggestion: Indent all new code with 4 spaces. Whoever touches code in a certain place should re-indent at least the surrounding block if necessary, so that all code blocks are indented consistently.
Tested with [one PR](https://github.com/Philipp91/fints-hbci-php/pull/6) that contains new tabs ([Travis fails](https://github.com/Philipp91/fints-hbci-php/pull/6)) and [another PR](https://github.com/Philipp91/fints-hbci-php/pull/7) that replaces old tabs …
=> Add a Travis check against new tabs for indentation

Samples/accounts.php, Samples/directDebit.php, Samples/saldo.php, Samples/standingOrderDelete.php, Samples/standingOrders.php, Samples/statement_of_account.php, Samples/transfer.php, Samples/variables.php, lib/Fhp/Connection.php, lib/Fhp/FinTs.php, lib/Fhp/FinTsInternal.php
This is a breaking change for the FinTs interface (constructor).
The port was not used anywhere, just being passed around. If the need should ever arise in future to customize the port, it should become part of the URL parameter.
=> Remove port number as parameter from FinTs and Connection

lib/Fhp/Connection.php, lib/Fhp/CurlException.php, lib/Fhp/Dialog/Dialog.php
Instead of accepting the request data as an AbstractMessage and returning the response as a string, Connection now handles both as raw strings. Besides being a cleaner abstraction layer, this also allows sending messages that do not inherit from AbstractMessage.
Also, change library name in `User-Agent` header to `"phpFinTS"` and clean up some unused code around those files.
=> Make Connection independent of AbstractMessage

lib/Fhp/Segment/BaseDescriptor.php, lib/Fhp/Segment/SegmentDescriptor.php, lib/Fhp/Syntax/Delimiter.php, lib/Fhp/Syntax/Parser.php, lib/Fhp/Syntax/Serializer.php, lib/Tests/Fhp/Syntax/ParserTest.php
This PR integrates the existing `Bin` type into the new `Parser`, and teaches the `splitEscapedString()` function to skip past nested syntax characters.
(Previously, the library used a [hack](https://github.com/nemiah/phpFinTS/blob/415847715b48d92810e1c486456605f78615455e/lib/Fhp/Response/Response.php#L426) to parse the binary field inside `HNVSD`, which relies on the fact that the binary field is the last field inside that segment, so that there will be two subsequent segment terminators `'`. This would not work with encryption, however.)
=> Support parsing and serialization of binary blocks

lib/Fhp/Segment/BaseDescriptor.php, lib/Fhp/Segment/BaseGeschaeftsvorfallparameter.php, lib/Fhp/Segment/HITANS/HITANSv1.php, lib/Fhp/Segment/HITANS/HITANSv2.php, lib/Fhp/Segment/HITANS/HITANSv3.php, lib/Fhp/Segment/HITANS/HITANSv4.php, lib/Fhp/Segment/HITANS/HITANSv5.php, lib/Fhp/Segment/HITANS/HITANSv6.php, lib/Fhp/Segment/SegmentDescriptor.php, lib/Fhp/Syntax/Parser.php, lib/Fhp/Syntax/Serializer.php, lib/Tests/Fhp/Segment/HITANSTest.php
This allows us to stop treating BaseSegment.segmentkopf as a special case in parsing/serialization.
Add a common BaseGeschaeftsvorfallparameter sub-class for the HIxyzS segments, which all have the same fields/structure but different segment identifiers.
=> Include segment/DEG fields from super classes, add BaseGeschaeftsvorfallparameter

lib/Fhp/Segment/AnonymousSegment.php, lib/Fhp/Segment/BaseSegment.php, lib/Fhp/Syntax/Parser.php, lib/Fhp/Syntax/Serializer.php, lib/Tests/Fhp/Segment/AnonymousSegmentTest.php
Bank servers send segments in their responses that are not implemented in this library, and that do not need to be implemented either. In order for the parsing to succeed, unknown segments cannot be rejected. Instead of silently dropping them, this commit adds an AnonymousSegment class that holds their contents, which can be useful for debugging. 
Move the logic that detects the segment type from BaseSegment::parse() into the Parser where it belongs. Add a new AnonymousSegment class, which is returned from the Parser in case the parsed segment type is not explicitly implemented.
=> Add support for anonymous segments

lib/Fhp/Segment/BaseDeg.php, lib/Fhp/Segment/BaseDescriptor.php, lib/Fhp/Syntax/Parser.php, lib/Fhp/Syntax/Serializer.php, lib/Tests/Fhp/Segment/HITABTest.php, lib/Tests/Fhp/Segment/SegmentComparator.php, lib/Tests/Fhp/Syntax/ParserTest.php, lib/Tests/Fhp/Syntax/SerializerTest.php, lib/Tests/phpunit_bootstrap.php, phpunit.xml.dist
Unit test coverage through HITABTest, need to add support for the abbreviated `TAB` namespace (the segment definition were already part of a previous PR) and need to fix assertEquals() in unit tests for segments.
=> Treat absent nested DEGs correctly in Parser/Serializer

lib/Fhp/Message/Message.php, lib/Fhp/Protocol/Message.php, lib/Fhp/Protocol/MessageBuilder.php, lib/Fhp/Segment/BaseSegment.php, lib/Fhp/Segment/SegmentInterface.php, lib/Fhp/Syntax/Parser.php, lib/Tests/Fhp/Segment/AnonymousSegmentTest.php
There is already a `Fhp\Message\Message` class, which will eventually be replaced by the new `Fhp\Protocol\Message` class. The difference is that the former contains unstructured segments as strings in their serialized wire format, whereas the latter contains segments as structured instances of `BaseSegment` sub-classes. For compatibility during the transition period, both implement the same `SegmentInterface`.
=> Add Fhp\Protocol\Message and MessageBuilder

lib/Fhp/FinTs.php, lib/Fhp/MT940/MT940.php
`MT940` is now both a class name and a namespace name. Just using `use` declarations for every used class instead of relying on namespace-relative class references to work is the more future-proof and reliable solution, and it also makes the out-of-namespace dependencies clearly visible at the top of the file.
=> Fix for bad class reference caused by PR #100

lib/Tests/Fhp/SanitizingCLILogger.php, lib/Tests/Fhp/SanitizingCLILoggerTest.php, prettify_message.php, prettify_segment.php
The logger removes sensitive information like PINs from the log output without breaking the wire format. The inspect tools read a serialized message or segment from the command line and print it as a parsed tree structure, or allow viewing it in an interactive debugger.
@ampaze fyi
=> Add some development tools to log and inspect segments and messages

lib/Fhp/Dialog/Dialog.php
$tanMechanism ist bereits ein Array, wenn gesetzt. Das nochmal in ein Array zu packen führt zu:
Fatal Error: Method Fhp\Segment\HNSHK::__toString() must not throw an exception
wegen
Array to string conversion
=> $tanMechanism is already an array

Samples/accounts.php, Samples/directDebit.php, Samples/saldo.php, Samples/standingOrderDelete.php, Samples/standingOrders.php, Samples/statement_of_account.php, Samples/transfer.php, lib/Fhp/Dialog/Dialog.php, lib/Fhp/FinTs.php, lib/Fhp/FinTsInternal.php, lib/Fhp/Message/Message.php, lib/Tests/Fhp/Message/MessageTest.php
* Explizite Methode zum Dialog initialisieren
* beim Dialog::sync keine Sicherheitsfunktion verwenden, somit sollte dort auch keine TAN verlang werden,
* pro Dialog eine eindeutige Sicherheitsfunktion verwenden
* getAccounts ohne separaten Dialog::init
=> Explizite Methode zum Dialog initialisieren

lib/Fhp/FinTs.php
Import der Klasse fehlt für Zeile 746:
https://github.com/nemiah/phpFinTS/blob/a727eb0afebefdbd7f56c94539449096067c6031/lib/Fhp/FinTs.php#L746
=> Add missing class import

lib/Fhp/Connection.php, lib/Fhp/Protocol/Message.php, lib/Fhp/Protocol/MessageBuilder.php, lib/Fhp/Segment/BaseDeg.php, lib/Fhp/Segment/BaseSegment.php, lib/Fhp/Syntax/Parser.php
Note: These changes are based on a58dd3aa0a919c175bdf6194f472e321f4e77f3e, assuming that a727eb0afebefdbd7f56c94539449096067c6031 is (partially) rolled back.
See the commit messages for details.
=> Various improvements to Connection, Message and BaseDeg

.travis.yml, csfixer-check.sh
This is untested. OTOH, Travis output doesn't appear on GitHub anyways and can be ignored, so we could move forward with this and see how it behaves.
=> #109 Add CS Fixer to Travis

lib/Fhp/BaseAction.php, lib/Fhp/FinTsNew.php, lib/Tests/Fhp/FinTsTestCase.php, lib/Tests/Fhp/Integration/Consors/ConsorsIntegrationTestBase.php, lib/Tests/Fhp/Integration/DKB/DKBIntegrationTestBase.php, lib/Tests/Fhp/Integration/DKB/GetStatementOfAccountTest.php
This is required with most banks to submit a TAN within the same dialog in which it was requested. In particular, those banks to not require any dialog initialization after re-opening the physical connection when the TAN is available.
This makes GetStatementOfAccount with a TAN work for DKB, add integration test.
See #157 for discussion.
@ampaze fyi
=> Include UPD, Dialog-ID and message number in FinTs persisted state

lib/Fhp/FinTsNew.php, lib/Fhp/Protocol/ServerException.php, lib/Fhp/Segment/HIRMS/Rueckmeldungscode.php
Closes #181
They are global errors that regularly accompany per-action errors without providing more relevant information. Extracting them prevents throwing a ServerException from execute() or submitTan() that only contains these two error codes and no further information. In case of 9800, the bank closed the dialog, so we consider it closed too.
=> Handle response codes 9050/9800 correctly

lib/Fhp/FinTsNew.php, lib/Tests/Fhp/Integration/Consors/ConsorsIntegrationTestBase.php, lib/Tests/Fhp/Integration/DKB/DKBIntegrationTestBase.php, lib/Tests/Fhp/Integration/InitializationErrorTest.php
Closes #179
Instead allow storing a plain int (the Tan mode's ID) in the $selectedTanMode field and resolve it later (during login(), execute() or submitTan()), when the application expects server requests to happen anyway. This also means that selectTanMode() won't throw exceptions anymore.
=> Don't call bank for selectTanMode()

lib/Fhp/Action/GetStatementOfAccount.php, lib/Fhp/Action/GetStatementOfAccountXML.php, lib/Fhp/FinTsNew.php, lib/Fhp/FinTsOptions.php, lib/Fhp/Protocol/Message.php, lib/Fhp/Protocol/ServerException.php, lib/Fhp/Segment/BaseDeg.php, lib/Fhp/Segment/BaseDescriptor.php, lib/Fhp/Segment/BaseSegment.php, lib/Fhp/Segment/CAZ/HKCAZv1.php, lib/Fhp/Segment/DegDescriptor.php, lib/Fhp/Segment/HIRMS/FindRueckmeldungTrait.php, lib/Fhp/Segment/HIRMS/Rueckmeldung.php, lib/Fhp/Segment/KAZ/HKKAZv4.php, lib/Fhp/Segment/KAZ/HKKAZv5.php, lib/Fhp/Segment/KAZ/HKKAZv6.php, lib/Fhp/Segment/KAZ/HKKAZv7.php, lib/Fhp/Segment/SegmentDescriptor.php, lib/Fhp/Syntax/Parser.php, lib/Fhp/Syntax/Serializer.php, lib/Tests/Fhp/FinTsTestCase.php, lib/Tests/Fhp/SanitizingCLILogger.php
See also https://dev.to/aleksikauppila/using-isset-and-empty-hurts-your-code-aaa and the two commit messages. I'm replacing mostly in the newer code that I authored, where I can be sure that the replacement is equivalent.
@ampaze @fbett @nemiah Any opinions from PHP experts? It just seems to me that silently swallowing typos and removed/renamed variables isn't a good idea. Maybe we want to replace occurrences in the remainder of the codebase as well.
=> Replace some isset() and empty() calls with safer alternatives

lib/Fhp/Segment/Common/Kik.php, lib/Fhp/Segment/Common/Kti.php, lib/Tests/Fhp/Segment/HKCCSTest.php
Matches the specification. Not all banks require a BIC, but the specification does, and banks that don't only respond with cryptic error messages, so it's easier for users if validation fails early with a clear message.
=> Add validation to Kik/Kti

lib/Fhp/Action/GetStatementOfAccount.php, lib/Tests/Fhp/Integration/Consors/GetStatementOfAccountTest.php, lib/Tests/Fhp/Integration/DKB/GetStatementOfAccountTest.php
Consorsbank sends it like this, even though it should be ISO-8859.
=> Tolerate UTF-8-encoded MT940 data

lib/Fhp/Segment/SPA/GetUnterstuetzteSepaDatenformateTrait.php, lib/Fhp/Segment/SPA/ParameterSepaKontoverbindungAnfordernV1.php, lib/Fhp/Segment/SPA/ParameterSepaKontoverbindungAnfordernV2.php
=> Bei SEPA Überweisungen auch von der Bank gemeldete XML Formate der Form sepade.pain.00x.001.0y.xsd unterstützen

lib/Fhp/Segment/DME/HIDMESv1.php, lib/Fhp/Segment/DME/HIDMESv2.php, lib/Fhp/Segment/DSE/HIDSESv1.php, lib/Fhp/Segment/DSE/HIDSESv2.php
This should fix current Travis failures on `master`.
=> Fix PHP7.3 compatibility of return type hints

lib/Fhp/FinTsNew.php
It can be useful for application code, because the TanMode object contains information about the TAN format (allowed characters, maximum length) that the TanRequest does not contain.
=> Make FinTsNew::getSelectedTanMode() public

lib/Fhp/Action/SendSEPATransfer.php, lib/Fhp/Segment/HIRMS/Rueckmeldungscode.php
@Philipp91 Warum gibt es bei SendSEPATransfer diese extra Prüfung überhaupt? Es würde doch bei einem Fehler eh eine ServerException geben. Und bei keinem Fehler eben nicht.
=> Überweisungen können auch ohne TAN direkt ausgeführt werden

lib/Fhp/FinTs.php, lib/Fhp/FinTsInternal.php
This patch fixes the broken TAN based statement fetch for transactions that are older than 4 weeks.
The library function "getUsedPinTanMechanism" returns an array but result is handled as integer; I renamed it to "getUsedPinTanMechanisms" and let users of this function extract the first element.
=> (urgent) Fix TAN mechanism array vs. integer (this fixes TAN based statement fetch)

DEVELOPER-GUIDE.md, SamplesNew/login.php, lib/Fhp/FinTsNew.php, lib/Fhp/FinTsOptions.php, lib/Fhp/Options/SanitizingLogger.php, lib/Tests/Fhp/CLILogger.php, lib/Tests/Fhp/Options/SanitizingLoggerTest.php, lib/Tests/Fhp/SanitizingCLILogger.php
See the commit messages for more details. `FinTsNew::setLogger()` is the new way to set the logger.
=> Split SanitizingCLILogger, enforce its use and remove from FinTsOptions

csfixer-check.sh
#227 has shown, that Travis does not fully execute the script "csfixer-check.sh"
In a consequence the coding styles are not validated.
Travis job protocol to #227:
https://travis-ci.com/nemiah/phpFinTS/jobs/280889151
Error message:
````
fatal: ambiguous argument '': unknown revision or path not in the working tree.
````
Cause:
Travis does not set $COMMIT_RANGE and "" is not accepted by git diff, but an empty string without double quote is.
Problem:
The script does not return an error code > 0 in this case, so the Travis result keeps untouched (valid).
This PR includes several improvements:
- Check result of "vendor/bin/php-cs-fixer", output an error message and exit with error code 1, if an error occurs
- Use of Travis environment variable "$TRAVIS_COMMIT_RANGE" including workaround, if …
=> Fix csfixer check

lib/Fhp/Action/GetSEPAAccounts.php, lib/Fhp/Segment/HNSHK/HNSHKv4.php, lib/Tests/Fhp/Integration/Postbank/GetSEPAAccountsTest.php, lib/Tests/Fhp/Integration/Postbank/InitDialogWithBlockedPinTest.php, lib/Tests/Fhp/Integration/Postbank/InitEndDialogTest.php, lib/Tests/Fhp/Integration/Postbank/PostbankIntegrationTestBase.php
Fixes #231.
This is based on @ampaze's integration test for the Postbank, where I temporarily disabled the one test that isn't working yet (need to follow up in ~90days when we can test with the real bank again).
=> Postbank integration tests, fix for empty GetSEPAAccounts response

lib/Fhp/Action/GetStatementOfAccount.php, lib/Fhp/Action/GetStatementOfAccountXML.php
Fixes #198 
They are needed for subsequent requests in case of paginated responses.
=> #198 Serialize action parameters in GetStatementOfAccount

lib/Fhp/FinTsNew.php, lib/Fhp/Protocol/BPD.php, lib/Tests/Fhp/Integration/Consors/GetStatementOfAccountTest.php, lib/Tests/Fhp/Integration/DKB/SendSEPATransferTest.php
The field is supposed to contain the segment identifier of the segment for which the authentication is needed. The specification requires setting it upon login for special PIN/TAN use cases, requires setting it to HKIDN for regular logins, but does not specify anything for regular requests.
Now Consorsbank starts requiring it to be set to HKKAZ for such requests, and possibly similarly for others. This commit changes the behavior accordingly. HKKAZ also still works for DKB.
=> Populate HKTAN.segmentkennung with the business transaction's segment name

lib/Fhp/Segment/BaseDescriptor.php
It was originally added for two reasons, both of which are not applicable anymore: Firstly, it seemed useful to skip some unnecessary fields in the specification and to be able to continue at a later field by specifying its absolute index. But in practice, it is much easier to just copy over all fields from the specification than to fiddle with index magic and off-by-one errors. Secondly, it seemed necessary to declare the indices of fields behind a repeated field, e.g. a repeated field of length 100 occupies indices 0 through 99 and must thus be followed by index 100. But this use case is now supported implicitly as long as the repeated field specifies the @Max annotation, which is now mandatory.
=> Remove support for @Index annotations in field descriptors

lib/Fhp/Action/GetStatementOfAccount.php, lib/Fhp/FinTs.php, lib/Fhp/Model/Account.php, lib/Fhp/Model/StatementOfAccount/Statement.php, lib/Fhp/Model/StatementOfAccount/StatementOfAccount.php, lib/Fhp/Model/StatementOfAccount/Transaction.php, lib/Fhp/Response/GetStatementOfAccount.php
This decouples it from the old library's `Model` code and allows to remove its mutating accessors.
=> Move StatementOfAccount creation function to the class itself

lib/Fhp/Model/TanRequestChallengeImage.php
Kontext: #269
@fbett Kannst du bestätigen, dass echte TAN-Bilder immer größer als 20 Byte sind?
@dtvmedia Ist die Meldung so hilfreich? Und weißt du schon, ob HHD1.4 Flickercodes auch immer unter 20 Bytes sind? Der HHD1.3 Code, den du gepostet hast, war 10 Bytes.
=> More validation in TanRequestChallengeImage

Samples/login.php, lib/Fhp/BaseAction.php, lib/Fhp/FinTs.php, lib/Tests/Fhp/Integration/Consors/ConsorsIntegrationTestBase.php, lib/Tests/Fhp/Integration/DKB/GetStatementOfAccountTest.php, lib/Tests/Fhp/Integration/DKB/SendSEPATransferTest.php
The term "session" can easily be confused with PHP's session management mechanism ($_SESSION etc.). Use the term "execution" or "process" instead, whichever fits best in the respective context.
See #271 @ampaze fyi
=> Replace "PHP session" with "PHP execution or "PHP process"

lib/Fhp/Segment/SAL/HISALv7.php
Der `buchungszeitpunkt` ist optional (zumindest bei der `GetBalance` Operation). Da bspw. die Volksbank hier keinen `buchungszeitpunkt` meldet erhält man eine "Invalid response from server" Exception
=> Bug in HISALv7

lib/Fhp/Action/GetBalance.php, lib/Fhp/Action/GetSEPAAccounts.php, lib/Fhp/Action/GetStatementOfAccount.php, lib/Fhp/Action/GetStatementOfAccountXML.php, lib/Fhp/BaseAction.php, lib/Fhp/FinTs.php, lib/Fhp/Options/SanitizingLogger.php, lib/Fhp/Protocol/DialogInitialization.php, lib/Fhp/Protocol/GetTanMedia.php, lib/Fhp/Protocol/Message.php, lib/Fhp/Protocol/UPD.php, lib/Fhp/Segment/BaseDeg.php, lib/Fhp/Segment/BaseSegment.php, lib/Fhp/Segment/HNHBK/BezugsnachrichtV1.php, lib/Fhp/Segment/HNHBS/HNHBSv1.php, lib/Fhp/Segment/HNSHK/HNSHKv4.php, lib/Fhp/Segment/HNVSK/HNVSKv3.php, lib/Fhp/Segment/Segmentkopf.php, lib/Fhp/Segment/TAN/HITANv6.php, lib/Fhp/Segment/TAN/VerfahrensparameterZweiSchrittVerfahrenV6.php, lib/Fhp/Syntax/Parser.php, lib/Fhp/Syntax/Serializer.php
phpDoc doesn't use `#` to mark member names, but rather `::` as the delimiter between class and member name, and no marker for members of the same class.
=> Fix {@link} references in phpDoc

Samples/directDebit_Sephpa.php, Samples/directDebit_phpSepaXml.php, Samples/login.php, Samples/transfer.php, lib/Fhp/BaseAction.php, lib/Fhp/FinTs.php, lib/Tests/Fhp/Integration/Consors/ConsorsIntegrationTestBase.php, lib/Tests/Fhp/Integration/DKB/DKBIntegrationTestBase.php, lib/Tests/Fhp/Integration/DKB/GetStatementOfAccountTest.php, lib/Tests/Fhp/Integration/DKB/SendSEPATransferTest.php, lib/Tests/Fhp/Integration/IngDiba/GetStatementOfAccountTest.php, lib/Tests/Fhp/Integration/IngDiba/IngDibaIntegrationTestBase.php, lib/Tests/Fhp/Integration/KSK/KSKIntegrationTestBase.php, lib/Tests/Fhp/Integration/Postbank/PostbankIntegrationTestBase.php
Fixes #282.
This also affects the behavior of login(). It takes the burden off the caller to remember and call ensureSuccess() separately. Though they still need to check for needsTan(), as per the new example code and documentation.
Also, stop wrapping ServerExceptions inside UnexpectedResponseExceptions within executeWeakDialogInitialization(), as this was just making it harder to access the ServerException's helpers like indicatesBadLoginData().
=> Call maybeThrowError() from execute() and submitTan()

Samples/tanModesAndMedia.php
An error occurred as soon as index "0" was selected as TAN Mode or TAN Medium.
I noticed the problem when I tried to select my first of two registered devices with TAN2Go (Mode 921) of DKB.
empty() is also false if the variable in question contains 0 or "0" (as string).
=> Fix Problem with [0] as Index in Sample

Samples/login.php, lib/Fhp/Action/GetBalance.php, lib/Fhp/Action/GetSEPAAccounts.php, lib/Fhp/Action/GetSEPADirectDebitParameters.php, lib/Fhp/Action/GetStatementOfAccount.php, lib/Fhp/Action/GetStatementOfAccountXML.php, lib/Fhp/BaseAction.php, lib/Fhp/FinTs.php, lib/Fhp/Protocol/GetTanMedia.php, lib/Fhp/Protocol/ServerException.php, lib/Tests/Fhp/Integration/DKB/DKBIntegrationTestBase.php, lib/Tests/Fhp/Integration/DKB/GetStatementOfAccountTest.php, lib/Tests/Fhp/Integration/DKB/SendSEPATransferTest.php, lib/Tests/Fhp/Integration/IngDiba/IngDibaIntegrationTestBase.php, lib/Tests/Fhp/Integration/KSK/KSKIntegrationTestBase.php, lib/Tests/Fhp/Integration/Postbank/PostbankIntegrationTestBase.php, lib/Tests/Fhp/Protocol/ServerExceptionTest.php
Summary: This is a breaking API change for the new library implementation (which hasn't been released yet). isSuccess() is now isDone() and ensureSuccess() is now ensureDone(). Other status indicators on BaseAction are removed, as they are now unnecessary (an action is either done or not, execute() throws all the errors). See #282 for discussion.
In practice, most library users will only want to execute() one action at a time, the library currently only supports one action anyway, and many banks might only support this too. This makes the distinction between per-action errors (where one action could fail and another could succeed within the same request) and request-level errors (where there was an issue with the overall request and none of the actions were even attempted) less important. …
=> Remove per-action error handling

lib/Fhp/Segment/Common/Sdo.php, lib/Fhp/Segment/DegDescriptor.php, lib/Fhp/Syntax/Parser.php, lib/Tests/Fhp/Segment/HISALTest.php
Fixes #304
Not sure if a similar fix is necessary for the DEG parsing function, though probably not because DEG field delimiters need to be present even for empty subfields for the indices of subsequent fields to match. So probably the existing $allowEmpy logic in the DEG parsing function handles the same case there, and thus this fix is only necessary on the segment level.
=> Fix parsing of segments with required but empty DEGs where all subfields are optional

lib/Fhp/Action/SendSEPADirectDebit.php
The request to send a SepaDirectDebit needs to be persisted for instance in case a wrong tan is entered.
Added serialize/unserialize functionality so the request can be persisted
=> Fix to persit SendSepaDirectDebit

lib/Fhp/Model/StatementOfAccount/StatementOfAccount.php, lib/Fhp/Model/StatementOfAccount/Transaction.php
Für eine RLS enthält die Textschlüsselergänzung den Rückgabegrund, für die weitere Auswertung kann es sinnvoll sein darauf zugreifen zu können.
=> Textschlüsselergänzung hinzufügen

lib/Fhp/MT940/MT940.php
Der Test auf einen leeren String ergibt an dieser Stelle nicht wirklich Sinn.
Nach der Definition des Regex oben enthält die zweite Matching-Group bereits einen nicht leeren String (ein oder mehr Zeichen).
Der einzige Fall bei dem dieser Test fälschlicherweise fehlschlägt ist bei dem String "0" (`empty("0")` ist `true`)
Das in einigen Fällen dazu, dass z.B. bei einer EREF die mit 0 Endet die 0 abgeschnitten wird.
=> remove check for empty string

lib/Fhp/FinTs.php, lib/Fhp/Model/NoPsd2TanMode.php, lib/Fhp/Model/TanMode.php, lib/Fhp/Model/TanRequest.php, lib/Fhp/Protocol/BPD.php, lib/Fhp/Protocol/DialogInitialization.php, lib/Fhp/Protocol/TanRequiredException.php, lib/Fhp/Segment/CAZ/HKCAZv1.php, lib/Fhp/Segment/CAZ/ParameterKontoumsaetzeCamt.php, lib/Fhp/Segment/HNVSK/SicherheitsidentifikationDetailsV2.php, lib/Fhp/Segment/KAZ/HKKAZv4.php, lib/Fhp/Segment/KAZ/HKKAZv5.php, lib/Fhp/Segment/KAZ/HKKAZv6.php, lib/Fhp/Segment/KAZ/HKKAZv7.php, lib/Fhp/Segment/SAL/HISALv6.php, lib/Fhp/Segment/SAL/HISALv7.php, lib/Fhp/Segment/SAL/HKSALv4.php, lib/Fhp/Segment/SPA/HKSPAv2.php, lib/Fhp/Segment/TAB/TanMediumListeV4.php, lib/Fhp/Segment/TAB/TanMediumListeV5.php, lib/Fhp/Segment/TAN/HITAN.php, lib/Fhp/Segment/TAN/HITANS.php, lib/Fhp/Segment/TAN/HITANSv6.php, lib/Fhp/Segment/TAN/HITANv6.php, lib/Fhp/Segment/TAN/HKTAN.php, lib/Fhp/Segment/TAN/HKTANFactory.php, lib/Fhp/Segment/TAN/HKTANv6.php, lib/Fhp/Segment/TAN/ParameterZweiSchrittTanEinreichung.php, lib/Fhp/Segment/TAN/ParameterZweiSchrittTanEinreichungV6.php, lib/Fhp/Segment/TAN/VerfahrensparameterZweiSchrittVerfahrenV6.php
See #309 for background and the individual commit messages for details.
This PR prepares the code base for adding HKTANv7 and support for decoupled strong authentication in a subsequent PR.
Breaking changes:
* Make `TanRequest::getChallenge()` nullable. Instead of returning `"nochallenge"`, return null. With HKTANv7, the field is nullable for decoupled modes anyway.
=> Various changes to prepare for HKTANv7 and decoupled strong authentication

Samples/accounts.php, Samples/balance.php, Samples/directDebit_Sephpa.php, Samples/directDebit_phpSepaXml.php, Samples/login.php, Samples/statementOfAccount.php, Samples/transfer.php, lib/Fhp/BaseAction.php, lib/Fhp/FinTs.php, lib/Fhp/Model/NoPsd2TanMode.php, lib/Fhp/Model/TanMode.php, lib/Fhp/Model/TanRequest.php, lib/Fhp/Segment/HIRMS/Rueckmeldungscode.php, lib/Fhp/Segment/TAN/HITANSv7.php, lib/Fhp/Segment/TAN/HITANv6.php, lib/Fhp/Segment/TAN/HITANv7.php, lib/Fhp/Segment/TAN/HKTAN.php, lib/Fhp/Segment/TAN/HKTANFactory.php, lib/Fhp/Segment/TAN/HKTANv6.php, lib/Fhp/Segment/TAN/HKTANv7.php, lib/Fhp/Segment/TAN/ParameterZweiSchrittTanEinreichungV7.php, lib/Fhp/Segment/TAN/VerfahrensparameterZweiSchrittVerfahrenV6.php, lib/Fhp/Segment/TAN/VerfahrensparameterZweiSchrittVerfahrenV7.php
See #309 for background.
While the integration tests ensure that no existing (HKTANv6-based) authentication is broken, the new decoupled authentication is entirely untested and based solely on the [new specification](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Security_Sicherheitsverfahren_PINTAN_2020-07-10_final_version.pdf) and specifically all the red parts in there.
Breaking Changes:
* `TanMode::getMaxTanLength()` and `TanMode::getTanFormat()` can now throw `\RuntimeException` (though they won't for existing "old" TanModes).
* There may now be TAN modes where `TanMode::isDecoupled()` returns `true`. Your application may want to filter out (not support) such TAN modes unless you explicitly implement support for decoupled modes (see `handleDecoupled()` in …
=> Add support for HKTANv7 and decoupled authentication

lib/Fhp/MT940/MT940.php
trim(null) is deprecated, but values of "$prepared" are nullable.
=> PHP8.1 changes

lib/Tests/Fhp/Model/FlickerTan/TanRequestChallengeFlickerTest.php
Gets rid of this warning:
```
$ composer update
Class Fhp\Model\FlickerTan\TanRequestChallengeFlickerTest located in ./vendor/nemiah/php-fints/lib/Tests/Fhp/Model/FlickerTan/TanRequestChallengeFlickerTest.php does not comply with psr-0 autoloading standard. Skipping.
```
=> Fix minor PSR-0 violation

lib/Fhp/Segment/Common/Kti.php
The fields are actually nullable and in ::fromAccount() we might receive nulls.
Fixes #405
=> Tolerate null values passed to Kti::create()

lib/Fhp/Action/GetSEPAAccounts.php, lib/Fhp/Segment/SPA/HISPASv3.php, lib/Fhp/Segment/SPA/HISPAv3.php, lib/Fhp/Segment/SPA/HKSPAv3.php, lib/Fhp/Segment/SPA/ParameterSepaKontoverbindungAnfordernV3.php
Das ist der Patch von @NabilHanna aus https://github.com/nemiah/phpFinTS/issues/391. Zusätzlich hat mir @ampaze noch erklärt wie man `ParameterSepaKontoverbindungAnfordernV3` anpasst.
Damit funktioniert bei mir die Abfrage von Kontostand und Transaktionshistorie mit Finanzen.net Zero/Baader Bank.
=> Unterstützung für "Segmentversion 3"

lib/Fhp/Model/StatementOfAccount/Statement.php, lib/Fhp/Model/StatementOfAccount/StatementOfAccount.php
Ich habe `Samples/statementOfAccount.php` mit ING ausprobiert: es gab Typ-Fehler und PHP Warnings.
Wenn ich das richtig sehe passiert das nur wenn es "vorgemerkte Umsätze" gibt. Mit den Änderungen hier funktioniert es aber einwandfrei.
=> ING-spezifische fixes

lib/Fhp/FinTs.php
Fixes #439, maybe. If it doesn't fix it, let's discard this pull request.
=> Reset DialogInitialization state when decoupled submission is still pending on login

lib/Fhp/Action/SendSEPARealtimeTransfer.php, lib/Fhp/Segment/IPZ/HIIPZSv1.php, lib/Fhp/Segment/IPZ/HIIPZSv2.php, lib/Fhp/Segment/IPZ/HIIPZv1.php, lib/Fhp/Segment/IPZ/HIIPZv2.php, lib/Fhp/Segment/IPZ/HKIPZv1.php, lib/Fhp/Segment/IPZ/HKIPZv2.php, lib/Fhp/Segment/IPZ/ParameterSEPAInstantPaymentZahlungV1.php, lib/Fhp/Segment/IPZ/ParameterSEPAInstantPaymentZahlungV2.php
Ich konnte nur Segment Version 1 testen, aber der einzige Unterschied zu Version 2 ist die Möglichkeit der Bank zu erlauben die Echtzeit Überweisung automatisch in eine "normale" Überweisung umzuwandeln, wenn die Zielbank keine Echtzeit Überweisung unterstützt.
closes #438
=> Unterstützung für Echtzeitüberweisung

lib/Fhp/FinTs.php
Fixes #412. Fixes #442.
The spec technically mandates that such a HITAN is sent on success, but in practice some banks don't do so, forcing us to adjust. Fortunately, the presence/absence of the 3956 respnose code is sufficient to tell whether the submission is already complete or not, so we rely (only) on that now.
=> Patch checkDecoupledSubmission() to tolerate absent HITAN(2) on success

Samples/directDebit_phpSepaXml.php
1) The used nemiah\phpSepaXml library was changed. 
Type was move from the SEPADirectDebitBasic to the addDebitor defintion
2) Type was changed from COR1 to CORE since COR1 does not seem to work
3) The default pain format pain.008.003.02 is no longer valid and hence the call to toXML the current format pain.008.001.02 was added to overwrite the default.
=> Example for SEPADirectDebitBasic.php is broken because of changed nemiah\phpSepaXml library

lib/Fhp/Segment/CME/HICMEv1.php, lib/Fhp/Segment/CSE/HICSEv1.php
This fixes an error with scheduled SEPA transfers.
The HICSE/HICME segment response from the bank was parsed incorrectly, throwing an InvalidResponseException ('Invalid Response from serverInvalid int: <string>') after the Bank accepted the transfer.
This occured because the HICSEv1/HICMEv1 classes inherited additional integer properties from BaseGeschaeftsvorfallparameter, which the parser is looking for in vain while reading the one string parameter of HICME.
In contrast, the HICMESv1 and HICSESv1 segments are correctly inherited from BaseGeschaeftsvorfallparameter.
=> HICME and HICSE segments are not Geschaeftsvorfaelle (unlike HICxES)

.github/workflows/tests.yml, lib/Fhp/Action/SendSEPADirectDebit.php, lib/Tests/Fhp/Unit/SendSEPADirectDebitTest.php, lib/Tests/resources/pain.008.002.02.xml
Fixes https://github.com/nemiah/phpFinTS/issues/490
this PR adds lazy quantifiers to the regex validating CtrlSum and others in SendSEPADirectDebit.
- The first commit has a failing test (I didn't know the package didn't have a CI pipeline) 
- The second commit creates a CI pipeline
- The third commit adds a code fix - and test passes.
=> Fixes sending large SEPA XMLs
