lib/Fhp/Connection.php
lib/Fhp/Response/Response.php

Segmentabhängige Zeichensatzkonvertierung resolves #7

Segmentabhängige Zeichensatzkonvertierung

---

lib/Fhp/FinTs.php
lib/Fhp/FinTsInternal.php
lib/Fhp/Parser/Dialect/PostbankMT940.php
lib/Fhp/Parser/Dialect/SpardaMT940.php
lib/Fhp/Response/GetStatementOfAccount.php

Automatische Verwendung von bekannten MT940 Dialekten, Dialekte für Sparda und Postbank #11

MT940 Dialekte

---

lib/Fhp/FinTs.php
lib/Fhp/FinTsInternal.php
lib/Fhp/Segment/HKEND.php
lib/Fhp/Segment/HNHBK.php

Diese kommt vom Server und kann Sonderzeichen enthalten.

Dialog-ID escapen

---

lib/Fhp/Model/StatementOfAccount/Transaction.php
lib/Fhp/Parser/MT940.php

Cherry-picked from mschindler83/fints-hbci-php.

Two minor fixes for structeredDescription

---

composer.json
lib/Fhp/Dialog/Dialog.php
lib/Fhp/Dialog/Exception/FailedRequestException.php
lib/Fhp/FinTs.php
lib/Fhp/Response/GetVariables.php
lib/Tests/Fhp/ResponseTest/GetVariablesTest.php

I hope this works for all cases. I would welcome more unit test cases, though. The tests currently contain real data from Sparkasse and Postbank.

Fix tan method parsing

---

lib/Fhp/FinTsInternal.php

I missed a reference to `Dialog::supportedTanMechanisms` which causes an error. This PR fixes it.

Fix getUsedPinTanMechanism

---

lib/Fhp/Dialog/Dialog.php
lib/Fhp/FinTs.php
lib/Fhp/FinTsInternal.php
lib/Fhp/Response/Response.php
lib/Fhp/Segment/HKTAN.php

Der Code ist via `getSaldo()` und `getSepaAccounts()` getestet mit Sparkasse, Postbank und Volksbank. Leider kam es dabei bei mir noch zu keiner TAN-Abfrage selber, aber wenn ich das richtig verstehe, muss man sich eh nur einmal mit dem gleichen TAN-Verfahren bei seiner Bank einloggen. Sonst hätte ich ja mindestens einmal eine TAN angeben müssen.

Fix postbank and tan mechanisms

---

lib/Fhp/Message/AbstractMessage.php
lib/Fhp/Message/Message.php
lib/Fhp/Response/Response.php
lib/Fhp/Segment/BaseDeg.php
lib/Fhp/Segment/BaseSegment.php
lib/Fhp/Segment/SegmentInterface.php
lib/Tests/Fhp/Segment/HITANSTest.php
lib/Tests/Fhp/Segment/HIUPDTest.php

See individual commits for details.

Various minor improvements

---

lib/Fhp/Response/GetVariables.php
lib/Fhp/Segment/HIRMG/HIRMGv2.php
lib/Fhp/Segment/HIRMS/HIRMSv2.php
lib/Fhp/Segment/HIRMS/Rueckmeldung.php
lib/Fhp/Segment/HIRMS/Rueckmeldungscode.php
lib/Tests/Fhp/ResponseTest/GetVariablesTest.php

As a side effect, this fixes the unit test breakage from #56.

Implement GetVariables with new HIRMS/3920 segment

---

README.md

Danke für deinen Fork! Warte aktuell noch darauf, dass meine Registrierung bei allen Banken ankommt, bin da aber guter Dinge dass dann wieder alles läuft.
Da mir das als Laie in Bankendingen mit der Registrierung nicht ganz klar war, hab ich die README dahingehend noch ein bisschen angepasst.

added more details to the readme about the registration

---

lib/Fhp/FinTs.php

Nun gibt `getTANDevices()` ein Array mit den Namen der TAN-Geräte zurück, die für `setTANMechanism()` genutzt werden können
Vorher: 
[TANMediaNames] => Array
(
[0] => G:1:cT?:Vorname Nachname_0:00:::::::::cT?:Vorname Nachname_0
[1] => M:1:::::::::::mT?:MFN1:*******1234
[2] => G:1:SO?:MyHandy:00:::::::::SO?:MyHandy
)
Jetzt:
[TANMediaNames] => Array
(
[0] => cT?:Vorname Nachname_0
[1] => mT?:MFN1
[2] => SO?:MyHandy
)

getTANDevices() finished

---

lib/Fhp/FinTs.php
lib/Fhp/FinTsInternal.php

Das Escape-Zeichen musste noch bei getTANDevices() raus

---

lib/Fhp/FinTs.php
lib/Fhp/Parser/Dialect/SpardaMT940.php
lib/Fhp/Parser/MT940.php
lib/Fhp/Response/GetStatementOfAccount.php

See the commit messages for details.

Several improvements to the MT940 parser

---

lib/Fhp/Model/TanMedium.php
lib/Fhp/Model/TanMode.php
lib/Fhp/Segment/Common/KtvV3.php
lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV1.php
lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV2.php
lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV3.php
lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV4.php
lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV5.php
lib/Fhp/Segment/HITANS/VerfahrensparameterZweiSchrittVerfahrenV6.php
lib/Fhp/Segment/TAB/HITAB.php
lib/Fhp/Segment/TAB/HITABSv4.php
lib/Fhp/Segment/TAB/HITABSv5.php
lib/Fhp/Segment/TAB/HITABv4.php
lib/Fhp/Segment/TAB/HITABv5.php
lib/Fhp/Segment/TAB/HKTABv4.php
lib/Fhp/Segment/TAB/HKTABv5.php
lib/Fhp/Segment/TAB/TanMediumListe.php
lib/Fhp/Segment/TAB/TanMediumListeV4.php
lib/Fhp/Segment/TAB/TanMediumListeV5.php

These are needed to retrieve available TAN media, so that the user can pick one.

Add TanMedium interface and HKTAB/HITAB/HITABS segments

---

lib/Fhp/Dialog/Dialog.php
lib/Fhp/FinTs.php
lib/Fhp/FinTsInternal.php
lib/Fhp/Protocol/BPD.php

Nachrichten an die Bank bekommen je nach Informationen in HIPINS automatisch ein HKTAN Segment
Dank an @Philipp91 für die große Vorarbeit 👍 
Closes #95

HKTAN automatisch via HIPINS

---

lib/Fhp/Dialog/Dialog.php
lib/Fhp/Protocol/Message.php

BPD bei der Dialog-Initialisierung aktualisieren

---

lib/Fhp/Protocol/BPD.php

fix wrong access of logger in options

Logger is now inside an option array

---

Samples/accounts.php
Samples/directDebit.php
Samples/saldo.php
Samples/standingOrderDelete.php
Samples/standingOrders.php
Samples/statement_of_account.php
Samples/transfer.php
lib/Fhp/Dialog/Dialog.php
lib/Fhp/FinTs.php

initializeDialog umbenennen in login

---

lib/Fhp/Dialog/Dialog.php

Sorry, da war ich zu schnell mit dem Pull Request #133

Bugfix: das Response Objekt zurückliefern

---

lib/Fhp/Dialog/Dialog.php
lib/Fhp/Dialog/Exception/TANRequiredException.php
lib/Fhp/FinTs.php
lib/Fhp/Message/Message.php
lib/Fhp/Response/Response.php

* TANRequiredException
* submitTanForMechanism
* TANToken für einfachere Handhabung

TAN Behandlung mit Unterbrechung der Verbindung

---

lib/Fhp/Segment/HKSAL.php
lib/Tests/Fhp/Message/MessageTest.php

It was broken in 90e15a0 (#135)

Fix MessageTest

---

lib/Fhp/Connection.php
lib/Fhp/CurlException.php
lib/Fhp/Protocol/ServerException.php
lib/Fhp/Segment/AnonymousSegment.php
lib/Fhp/Segment/BaseSegment.php
lib/Fhp/Segment/HIRMS/Rueckmeldung.php
lib/Fhp/Segment/HIRMS/Rueckmeldungscode.php
lib/Fhp/Segment/HKSAL.php
lib/Fhp/UnsupportedException.php
lib/Tests/Fhp/Message/MessageTest.php
lib/Tests/Fhp/Protocol/ServerExceptionTest.php
lib/Tests/Fhp/Segment/AnonymousSegmentTest.php

To be used in upcoming commits. ServerException encapsulates the logic that deals with HIRMG/HIRMS segments.
Also a minor improvement for CurlException.

Add UnsupportedException and ServerException

---

.gitignore
.php_cs
composer.json
composer.lock

See [this branch](https://github.com/Philipp91/fints-hbci-php/tree/csfixer) for the resulting diffs.

#109 Configure PHP CS Fixer

---

lib/Fhp/Dialog/Dialog.php
lib/Fhp/Dialog/Exception/TANRequiredException.php
lib/Fhp/Message/AbstractMessage.php
lib/Fhp/Message/Message.php
lib/Fhp/Response/GetTANRequest.php

… System-Id und Dialog-Id nicht wie üblich ermittelt werden.

Bugfix und Verbesserungen für TAN mit vorheriger Unterbrechung

---

lib/Fhp/Dialog/Dialog.php

$interval was not defined anymore which leads to errors when it is used. I have set it to 1 second.

$interval was not defined anymore

---

lib/Fhp/Dialog/Dialog.php

remove array conversion of $tanMachanism

---

lib/Fhp/Protocol/DialogInitialization.php
lib/Fhp/Segment/HIRMS/Rueckmeldungscode.php
lib/Fhp/Segment/HISYN/HISYNv4.php
lib/Fhp/Segment/HKEND/HKENDv1.php
lib/Fhp/Segment/HKIDN/HKIDNv2.php
lib/Fhp/Segment/HKSYN/HKSYNv3.php
lib/Fhp/Segment/HKVVB/HKVVBv3.php
lib/Fhp/Segment/HNHBK/HNHBKv3.php
lib/Fhp/Segment/TAN/AntwortHhdUc.php
lib/Fhp/Segment/TAN/HKTANv6.php
lib/Fhp/Segment/TAN/ParameterChallengeKlasse.php

Note: Integration test coverage will follow in a subsequent pull request.

Add segments and BaseAction implementation for dialog initialization

---

lib/Fhp/Protocol/GetTanMedia.php

Note: Integration test coverage will follow in a subsequent pull request.

Add action GetTanMedia

---

lib/Fhp/Response/GetTANRequest.php
lib/Fhp/Segment/TAN/HITANv6.php

Bugfix: Für den Namen des Tan Mediums die Interface Methode verwenden

---

lib/Fhp/Dialog/Exception/TANRequiredException.php
lib/Fhp/Response/Response.php
lib/Fhp/Segment/HKTAN.php

Bugfixes: TANRequiredException nur werfen wenn wirklich eine TAN verlangt wurde

---

lib/Fhp/Protocol/UPD.php
lib/Fhp/Segment/HICAZ/HICAZv1.php
lib/Fhp/Segment/HIUPD/ErlaubteGeschaeftsvorfaelle.php
lib/Fhp/Segment/HIUPD/ErlaubteGeschaeftsvorfaelleV1.php
lib/Fhp/Segment/HIUPD/ErlaubteGeschaeftsvorfaelleV2.php
lib/Fhp/Segment/HIUPD/HIUPD.php
lib/Fhp/Segment/HIUPD/HIUPDv4.php
lib/Fhp/Segment/HIUPD/HIUPDv6.php

Fixes issue reported in https://github.com/nemiah/phpFinTS/pull/157#issuecomment-559701081

Read HIUPD correctly

---

lib/Fhp/Action/GetSEPAAccounts.php
lib/Fhp/Action/GetStatementOfAccount.php
lib/Fhp/Action/GetStatementOfAccountXML.php
lib/Fhp/BaseAction.php
lib/Fhp/FinTsNew.php
lib/Fhp/Protocol/DialogInitialization.php
lib/Fhp/Protocol/GetTanMedia.php
lib/Fhp/Protocol/Message.php
lib/Fhp/Protocol/ServerException.php
lib/Fhp/Segment/HIRMS/Rueckmeldungscode.php
lib/Tests/Fhp/FinTsTestCase.php
lib/Tests/Fhp/Protocol/ServerExceptionTest.php

See the individual commit messages for details.

Several refactorings around `BaseAction`

---

lib/Fhp/Protocol/ServerException.php
lib/Fhp/Segment/HIRMS/Rueckmeldungscode.php
lib/Fhp/Segment/TAB/TanMediumListeV4.php

Along with some advice for how the application using this library should react to such errors.

Add getters to detect high-level error categories to ServerException

---

lib/Fhp/Action/SendSEPATransfer.php
lib/Fhp/Protocol/BPD.php
lib/Fhp/Segment/CCS/HICCSSv1.php
lib/Fhp/Segment/CCS/HKCCSv1.php
lib/Fhp/Segment/HIRMS/Rueckmeldungscode.php
lib/Fhp/Segment/HKVVB/HKVVBv3.php
lib/Fhp/Segment/SPA/HISPA.php
lib/Fhp/Segment/SPA/HISPAS.php
lib/Fhp/Segment/SPA/HISPASv1.php
lib/Fhp/Segment/SPA/HISPASv2.php
lib/Fhp/Segment/SPA/ParameterSepaKontoverbindungAnfordern.php
lib/Fhp/Segment/SPA/ParameterSepaKontoverbindungAnfordernV1.php
lib/Fhp/Segment/SPA/ParameterSepaKontoverbindungAnfordernV2.php
lib/Tests/Fhp/Integration/DKB/SendSEPATransferTest.php

Works with DKB (at least the bank accepted and confirmed the transfer -- it hasn't actually been executed yet and doesn't show up on any statement currently).

Add SendSEPATransfer action

---

lib/Fhp/Action/GetStatementOfAccount.php
lib/Fhp/BaseAction.php
lib/Fhp/FinTsNew.php
lib/Fhp/Protocol/ServerException.php
lib/Fhp/Segment/KAZ/HKKAZv4.php
lib/Fhp/Segment/KAZ/HKKAZv5.php
lib/Fhp/Segment/KAZ/HKKAZv6.php
lib/Fhp/Segment/KAZ/HKKAZv7.php
lib/Tests/Fhp/Integration/DKB/GetStatementOfAccountTest.php

Works with DKB. Only implemented for the MT940 version, not sure how the merging works for XML. Maybe @ampaze can implement it for XML?

Add pagination support to the new library classes

---

lib/Fhp/Action/GetStatementOfAccount.php
lib/Fhp/FinTsNew.php
lib/Fhp/Protocol/Message.php
lib/Fhp/Segment/AnonymousSegment.php
lib/Fhp/Segment/BaseSegment.php
lib/Fhp/Segment/TAN/GueltigkeitsdatumUndUhrzeitFuerChallenge.php
lib/Tests/Fhp/Protocol/ServerExceptionTest.php

See the commit messages for details.

Some fixes and add `FinTsNew::forgetDialog()`

---

lib/Fhp/Action/GetStatementOfAccount.php
lib/Fhp/Action/GetStatementOfAccountXML.php
lib/Fhp/FinTsNew.php

Kleine Verbesserungen für FinTsNew

---

lib/Fhp/Action/SendSEPADirectDebit.php
lib/Fhp/Segment/Common/Btg.php

Verbesserungen für SendSEPADirectDebit Action

---

lib/Fhp/FinTsNew.php

Clarify error message when login() is called before selectTanMode()

---

lib/Fhp/FinTs.php

fixes nemiah/phpFinTS#208

---

lib/Fhp/BaseAction.php

Erfolgsmeldungstext für eine Action zur weiteren Verwendung vorhalten

---

lib/Fhp/BaseAction.php
lib/Fhp/Protocol/Message.php
lib/Fhp/Segment/HIRMS/FindRueckmeldungTrait.php
lib/Fhp/Segment/HIRMS/RueckmeldungContainer.php

Berücksichtigen von mehreren Rückmeldungen mit dem selben Code

---

SamplesNew/login.php
lib/Fhp/FinTsNew.php
lib/Fhp/Options/Credentials.php
lib/Fhp/Options/FinTsOptions.php
lib/Fhp/Options/SanitizingLogger.php
lib/Fhp/Protocol/DialogInitialization.php
lib/Fhp/Protocol/Message.php
lib/Fhp/Segment/HKIDN/HKIDNv2.php
lib/Fhp/Segment/HKVVB/HKVVBv3.php
lib/Fhp/Segment/HNSHK/HNSHKv4.php
lib/Fhp/Segment/HNVSK/HNVSKv3.php
lib/Tests/Fhp/FinTsTestCase.php
lib/Tests/Fhp/Integration/Consors/ConsorsIntegrationTestBase.php
lib/Tests/Fhp/Integration/DKB/GetStatementOfAccountTest.php
lib/Tests/Fhp/Integration/DKB/SendSEPATransferTest.php
lib/Tests/Fhp/Options/SanitizingLoggerTest.php
lib/Tests/Fhp/Segment/HNVSKTest.php

Make FinTsNew ctor compatible with old FinTs ctor, i.e. without FinTsOptions/Credentials

---

SamplesNew/directDebit.php

SampleNew: Debit credit (review)

---

lib/Fhp/Action/SendSEPADirectDebit.php
lib/Fhp/Segment/Common/Btg.php
lib/Fhp/Segment/DME/HKDMEv1.php

Betrag Datenelementgruppe repariert

---

lib/Fhp/FinTsNew.php
lib/Fhp/Model/NoPsd2TanMode.php
lib/Fhp/Protocol/BPD.php
lib/Fhp/Protocol/DialogInitialization.php
lib/Fhp/Protocol/Message.php
lib/Fhp/Segment/TAN/HKTANv6.php
lib/Tests/Fhp/FinTsTestCase.php
lib/Tests/Fhp/Integration/IngDiba/GetSEPAAccountsTest.php
lib/Tests/Fhp/Integration/IngDiba/GetStatementOfAccountTest.php
lib/Tests/Fhp/Integration/IngDiba/IngDibaIntegrationTestBase.php
lib/Tests/Fhp/Integration/IngDiba/InitEndDialogTest.php

Fixes #57
See commit descriptions for details.

Fix ING-DiBa by not sending TANs at all

---

SamplesNew/accounts.php
SamplesNew/directDebit_Sephpa.php
SamplesNew/directDebit_phpSepaXml.php
SamplesNew/login.php
SamplesNew/transfer.php

@ampaze @fbett fyi, I have moved your directDebit example to another file, so that we can also have one using the `phpSepaXml` library.

Update example code

---

DEVELOPER-GUIDE.md
lib/Fhp/Action/SendSEPADirectDebit.php
lib/Fhp/Action/SendSEPATransfer.php
lib/Fhp/Model/TanRequest.php
lib/Fhp/Model/TanRequestChallengeImage.php
lib/Fhp/Segment/BaseDescriptor.php
lib/Fhp/Segment/CAZ/HICAZv1.php
lib/Fhp/Segment/CCS/HKCCSv1.php
lib/Fhp/Segment/DME/HKDMEv1.php
lib/Fhp/Segment/DSE/HKDSEv1.php
lib/Fhp/Segment/ElementDescriptor.php
lib/Fhp/Segment/HKCCS.php
lib/Fhp/Segment/HKCDL.php
lib/Fhp/Segment/HKDSC.php
lib/Fhp/Segment/HKDSE.php
lib/Fhp/Segment/HNSHK/HashalgorithmusV2.php
lib/Fhp/Segment/HNVSD.php
lib/Fhp/Segment/HNVSD/HNVSDv1.php
lib/Fhp/Segment/HNVSK/VerschluesselungsalgorithmusV2.php
lib/Fhp/Segment/KAZ/HIKAZ.php
lib/Fhp/Segment/KAZ/HIKAZv4.php
lib/Fhp/Segment/TAN/HITANv6.php
lib/Fhp/Segment/TAN/HKTANv6.php
lib/Fhp/Syntax/Bin.php
lib/Fhp/Syntax/Parser.php
lib/Fhp/Syntax/Serializer.php
lib/Tests/Fhp/Protocol/ServerExceptionTest.php
lib/Tests/Fhp/Syntax/BinTest.php

Move Fhp\DataTypes\Bin to Fhp\Syntax\Bin

---

lib/Fhp/Action/SendSEPADirectDebit.php

Einzellastschriften als Sammellastschriften senden (um die Kontrollsumme nutzen zu können) optional machen
closes #285

Einzellastschriften als Sammellastschriften senden optional machen

---

DEVELOPER-GUIDE.md

See discussion in https://github.com/nemiah/phpFinTS/pull/291#issuecomment-647008135
@Cugar15 fyi

Clarify that field ordering matters in segment classes

---

lib/Fhp/Protocol/TanRequiredException.php
lib/Fhp/Segment/CAZ/HKCAZv1.php
lib/Fhp/Segment/CAZ/ParameterKontoumsaetzeCamt.php
lib/Fhp/Segment/HNVSK/SicherheitsidentifikationDetailsV2.php
lib/Fhp/Segment/KAZ/HKKAZv4.php
lib/Fhp/Segment/KAZ/HKKAZv5.php
lib/Fhp/Segment/KAZ/HKKAZv6.php
lib/Fhp/Segment/KAZ/HKKAZv7.php
lib/Fhp/Segment/SAL/HISALv6.php
lib/Fhp/Segment/SAL/HISALv7.php
lib/Fhp/Segment/SAL/HKSALv4.php
lib/Fhp/Segment/SPA/HKSPAv2.php
lib/Fhp/Segment/TAB/TanMediumListeV4.php
lib/Fhp/Segment/TAB/TanMediumListeV5.php

This should make the build green again.

Fix current CS Fixer errors

---

.gitignore
Samples/browser.php
Samples/login.php
lib/Fhp/Action/GetBalance.php

Unlike the other sample code, which runs synchronously on the command line, this new example has a UI shown in a browser.
Sadly none of my banks currently ask for a TAN, so I couldn't actually test that part.

Add browser.php sample

---

composer.json
composer.lock
phpunit.xml.dist

Also ran `phpunit --migrate-configuration`.

Update PhpUnit and php-cs-fixer for PHP8 compatibility

---

lib/Fhp/MT535/MT535.php
lib/Fhp/Model/StatementOfHoldings/Holding.php

The subsequent code fails because the brackets are missing in the regex

fix holdings

---

composer.json

Haven't tested it, but it should work, as they haven't changed the interface.

Allow psr/log v2 or v3

---

lib/Fhp/MT940/MT940.php

fix #367 + some minor code hardening in the same file

---

Samples/statementOfAccount.php
lib/Fhp/Action/GetStatementOfAccount.php
lib/Fhp/Segment/KAZ/HIKAZ.php
lib/Fhp/Segment/KAZ/HIKAZv4.php

…to include unbooked transactions again

Add option to GetStatementOfAccount::create()

---

lib/Fhp/Action/GetBalance.php
lib/Fhp/Action/GetDepotAufstellung.php
lib/Fhp/Action/GetStatementOfAccountXML.php
lib/Fhp/Action/SendSEPADirectDebit.php
lib/Fhp/BaseAction.php
lib/Fhp/FinTs.php
lib/Fhp/MT535/MT535.php
lib/Fhp/MT940/MT940.php
lib/Fhp/Model/FlickerTan/SvgRenderer.php
lib/Fhp/Protocol/DialogInitialization.php
lib/Fhp/Segment/CAZ/HKCAZv1.php
lib/Fhp/Segment/DSE/MinimaleVorlaufzeitSEPALastschrift.php
lib/Tests/Fhp/Segment/HICAZTest.php

Wrapped the PSR NullLoger in the FinTs Log Sanitizer

fix #384 NullLogger Inheritance

---

composer.json
lib/Fhp/Action/GetDepotAufstellung.php
lib/Fhp/Action/GetStatementOfAccount.php
lib/Fhp/Options/SanitizingLogger.php
lib/Fhp/Syntax/Parser.php
lib/Fhp/Syntax/Serializer.php
lib/Tests/Fhp/Integration/DKB/GetStatementOfAccountTest.php
lib/Tests/Fhp/Integration/GLS/GLSIntegrationTestBase.php
lib/Tests/Fhp/Integration/GLS/GetStatementOfAccountXMLTest.php
lib/Tests/Fhp/Integration/KSK/KSKIntegrationTestBase.php
lib/Tests/Fhp/Integration/Postbank/PostbankIntegrationTestBase.php
lib/Tests/Fhp/Segment/HIUPDTest.php
lib/Tests/Fhp/Segment/HKCCSTest.php
lib/Tests/Fhp/Segment/HNVSDTest.php
lib/Tests/Fhp/Syntax/ParserTest.php
lib/Tests/Fhp/Syntax/SerializerTest.php

Migrate away from utf8_encode() and utf8_decode()

---

.travis.yml
composer.json
lib/Fhp/Action/GetStatementOfAccount.php
lib/Fhp/MT940/Dialect/SpardaMT940.php
lib/Fhp/MT940/MT940.php
lib/Fhp/Segment/AnonymousSegment.php
lib/Fhp/Segment/BaseDescriptor.php
lib/Fhp/Segment/BaseSegment.php
lib/Fhp/Syntax/Parser.php
lib/Fhp/Syntax/Serializer.php
lib/Tests/Fhp/FinTsTestCase.php

Drop support for PHP7

---

lib/Fhp/FinTs.php

Tolerate multiple 3956 Rückmeldungen

---

lib/Fhp/FinTs.php

After finally receiving a https url for Commerzbank this was a final fix to get it working.

Fix getTanModes if allowed tan mode not in all tan modes

---

lib/Fhp/MT940/MT940.php
lib/Fhp/Model/StatementOfAccount/Statement.php
lib/Fhp/Model/StatementOfAccount/StatementOfAccount.php

Hi guys,
I added a new method getEndBalance to the Statement class to get the last balance of an account.
Any comments?

added getEndBalance to "Statement" after transactions request

---

lib/Fhp/MT535/MT535.php

This fixes the handling of `:98C::` in holding statements and `depotValue` missing decimals.

Fix depot value and holding time parsing
